name: Deploy

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: scire-front

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm ci

      - run: npx semantic-release

      - name: Read version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t $SERVICE_NAME:$VERSION .

      - name: Save image
        run: docker save $SERVICE_NAME:$VERSION | gzip > image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: image.tar.gz
          target: /home/ubuntu/

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < image.tar.gz
            docker tag $SERVICE_NAME:$VERSION $SERVICE_NAME:latest
            docker compose up -d
            docker image prune -f
